In [102]:
import numpy as np
import pandas as pd

In [103]:
df=pd.read_csv("/kaggle/input/datasets/ayagamal11/e-commerce-dataset/ecommerce_sales_34500.csv")

In [104]:
df.head()

,order_id,customer_id,product_id,category,price,discount,quantity,payment_method,order_date,delivery_time_days,region,returned,total_amount,shipping_cost,profit_margin,customer_age,customer_gender
0,O100000,C17270,P234890,Home,164.08,0.15,1,Credit Card,2023-12-23,4,West,No,139.47,7.88,31.17,60,Female
1,O100001,C17603,P228204,Grocery,24.73,0.00,1,Credit Card,2025-04-03,6,South,No,24.73,4.60,-2.62,37,Male
2,O100002,C10860,P213892,Electronics,175.58,0.05,1,Credit Card,2024-10-08,4,North,No,166.80,6.58,13.44,34,Male
3,O100003,C15390,P208689,Electronics,63.67,0.00,1,UPI,2024-09-14,6,South,No,63.67,5.50,2.14,21,Female
4,O100004,C15226,P228063,Home,16.33,0.15,1,COD,2024-12-21,6,East,No,13.88,2.74,1.15,39,Male

In [105]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34500 entries, 0 to 34499
Data columns (total 17 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   order_id            34500 non-null  object
 1   customer_id         34500 non-null  object
 2   product_id          34500 non-null  object
 3   category            34500 non-null  object
 4   price               34500 non-null  float64
 5   discount            34500 non-null  float64
 6   quantity            34500 non-null  int64
 7   payment_method      34500 non-null  object
 8   order_date          34500 non-null  object
 9   delivery_time_days  34500 non-null  int64
 10  region              34500 non-null  object
 11  returned            34500 non-null  object
 12  total_amount        34500 non-null  float64
 13  shipping_cost       34500 non-null  float64
 14  profit_margin       34500 non-null  float64
 15  customer_age        34500 non-null  int64
 16  customer_gender     34500 non-null  object
dtypes: float64(5), int64(3), object(9)
memory usage: 4.5+ MB

In [106]:
df.describe()

,price,discount,quantity,delivery_time_days,total_amount,shipping_cost,profit_margin,customer_age
count,34500.000000,34500.000000,34500.000000,34500.000000,34500.000000,34500.000000,34500.000000,34500.000000
mean,119.391632,0.049291,1.490725,4.814203,170.008494,6.152120,28.116505,43.474377
std,195.620477,0.069894,0.932270,1.242141,357.503014,2.389539,53.352947,14.980682
min,1.010000,0.000000,1.000000,3.000000,0.820000,0.000000,-6.200000,18.000000
25%,16.690000,0.000000,1.000000,4.000000,19.710000,4.420000,1.500000,31.000000
50%,45.660000,0.000000,1.000000,5.000000,56.820000,6.090000,10.550000,43.000000
75%,130.950000,0.100000,2.000000,6.000000,168.530000,7.830000,33.132500,56.000000
max,2930.470000,0.300000,5.000000,13.000000,12931.800000,15.650000,1536.170000,69.000000

In [107]:
df.dtypes

order_id               object
customer_id            object
product_id             object
category               object
price                 float64
discount              float64
quantity                int64
payment_method         object
order_date             object
delivery_time_days      int64
region                 object
returned               object
total_amount          float64
shipping_cost         float64
profit_margin         float64
customer_age            int64
customer_gender        object
dtype: object

In [108]:
df.isnull()

,order_id,customer_id,product_id,category,price,discount,quantity,payment_method,order_date,delivery_time_days,region,returned,total_amount,shipping_cost,profit_margin,customer_age,customer_gender
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34495,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
34496,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
34497,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
34498,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
34499,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [109]:
print(df.isnull().sum())

order_id              0
customer_id           0
product_id            0
category              0
price                 0
discount              0
quantity              0
payment_method        0
order_date            0
delivery_time_days    0
region                0
returned              0
total_amount          0
shipping_cost         0
profit_margin         0
customer_age          0
customer_gender       0
dtype: int64

In [110]:
df.duplicated().sum()

np.int64(0)

In [111]:
df['order_date'] = pd.to_datetime(df['order_date'])
print(df['order_date'])

0       2023-12-23
1       2025-04-03
2       2024-10-08
3       2024-09-14
4       2024-12-21
           ...
34495   2025-08-13
34496   2023-12-04
34497   2025-02-01
34498   2024-03-27
34499   2025-09-11
Name: order_date, Length: 34500, dtype: datetime64[ns]

In [112]:
invalid_quantity = df[df['quantity'] < 1]
print(invalid_quantity)


invalid_price=(df[df['price'] <= 0])
print(invalid_price)

invalid_discount=(df[(df['discount'] < 0) | (df['discount'] > 1)])
print(invalid_discount)


invalid_shipping_cost=(df[df['shipping_cost'] < 0])
print(invalid_shipping_cost)


invaled_age=df[(df['customer_age'] < 18) | (df['customer_age'] > 69)]
print(invaled_age)



invalid_delivery_day=df[df['delivery_time_days'] > 10]
print(invalid_delivery_day)

Empty DataFrame
Columns: [order_id, customer_id, product_id, category, price, discount, quantity, payment_method, order_date, delivery_time_days, region, returned, total_amount, shipping_cost, profit_margin, customer_age, customer_gender]
Index: []
Empty DataFrame
Columns: [order_id, customer_id, product_id, category, price, discount, quantity, payment_method, order_date, delivery_time_days, region, returned, total_amount, shipping_cost, profit_margin, customer_age, customer_gender]
Index: []
Empty DataFrame
Columns: [order_id, customer_id, product_id, category, price, discount, quantity, payment_method, order_date, delivery_time_days, region, returned, total_amount, shipping_cost, profit_margin, customer_age, customer_gender]
Index: []
Empty DataFrame
Columns: [order_id, customer_id, product_id, category, price, discount, quantity, payment_method, order_date, delivery_time_days, region, returned, total_amount, shipping_cost, profit_margin, customer_age, customer_gender]
Index: []
Empty DataFrame
Columns: [order_id, customer_id, product_id, category, price, discount, quantity, payment_method, order_date, delivery_time_days, region, returned, total_amount, shipping_cost, profit_margin, customer_age, customer_gender]
Index: []
     order_id customer_id product_id category  price  discount  quantity  \
1708  O101708      C10832    P237575  Fashion  22.14       0.0         2
7575  O107575      C14524    P223337  Fashion   7.46       0.0         1

     payment_method order_date  delivery_time_days region returned  \
1708    Credit Card 2024-04-14                  13   East       No
7575    Credit Card 2023-11-12                  12   East       No

      total_amount  shipping_cost  profit_margin  customer_age customer_gender
1708         44.28           7.21           8.29            48          Female
7575          7.46           3.89          -1.28            39          Female

In [113]:
Q1 = df['profit_margin'].quantile(0.25)
Q3 = df['profit_margin'].quantile(0.75)

IQR = Q3 - Q1
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR
outliers = df[ (df['profit_margin'] < lower_bound) |(df['profit_margin'] > upper_bound)]
print(outliers)

      order_id customer_id product_id     category   price  discount  \
18     O100018      C17831    P218405  Electronics  734.32      0.00
24     O100024      C15611    P247930       Sports  345.57      0.15
51     O100051      C13005    P243043         Home  195.87      0.00
53     O100053      C11899    P229316  Electronics  402.13      0.00
57     O100057      C11528    P246809         Home  167.21      0.00
...        ...         ...        ...          ...     ...       ...
34460  O134460      C10265    P232438       Sports  226.26      0.15
34467  O134467      C14416    P227891      Fashion   78.95      0.00
34473  O134473      C17379    P217724  Electronics  817.80      0.00
34493  O134493      C14637    P230371       Sports  109.45      0.00
34497  O134497      C12986    P204345  Electronics  323.64      0.00

       quantity payment_method order_date  delivery_time_days   region  \
18            2         Wallet 2025-06-20                   4    South
24            2     Debit Card 2024-04-16                   5  Central
51            4    Credit Card 2024-12-31                   5     West
53            2         PayPal 2024-01-24                   5    South
57            4         Wallet 2023-12-06                   3    North
...         ...            ...        ...                 ...      ...
34460         2         PayPal 2024-02-13                   4    North
34467         5     Debit Card 2024-01-17                   6    South
34473         1     Debit Card 2024-02-06                   5     East
34493         4     Debit Card 2024-08-17                   5     West
34497         5    Credit Card 2025-02-01                   6     East

      returned  total_amount  shipping_cost  profit_margin  customer_age  \
18          No       1468.64          10.90         165.34            58
24          No        587.47           9.48         166.76            32
51          No        783.48          10.37         209.00            43
53          No        804.26           9.93          86.58            40
57          No        668.84           8.88         178.40            37
...        ...           ...            ...            ...           ...
34460       No        384.64           8.66         106.73            56
34467      Yes        394.75           7.55         130.61            23
34473       No        817.80           9.06          89.08            32
34493       No        437.80           9.52         121.82            65
34497       No       1618.20          12.18         182.00            41

      customer_gender
18             Female
24             Female
51             Female
53             Female
57             Female
...               ...
34460          Female
34467            Male
34473          Female
34493            Male
34497          Female

[3025 rows x 17 columns]

In [114]:
df.groupby("category")["quantity"].sum()

category
Beauty         6122
Electronics    9343
Fashion        9148
Grocery        6031
Home           8229
Sports         6244
Toys           6313
Name: quantity, dtype: int64

In [115]:
df.groupby("region")["quantity"].sum()

region
Central     8392
East       10375
North      11310
South      11294
West       10059
Name: quantity, dtype: int64

In [116]:
df.groupby("category")["profit_margin"].mean()

category
Beauty         11.990395
Electronics    55.723587
Fashion        20.597162
Grocery        -2.264160
Home           47.864717
Sports         38.485114
Toys            7.927773
Name: profit_margin, dtype: float64

In [117]:
df.groupby("region")["profit_margin"].mean()

region
Central    28.058184
East       28.249600
North      27.534810
South      27.832433
West       28.993204
Name: profit_margin, dtype: float64

In [118]:
df.groupby("product_id").agg({'quantity':'sum','price':'sum'})

            quantity    price
product_id
P200000            1   133.15
P200001            1   168.11
P200002            3   119.18
P200003            2    91.73
P200005            2     6.80
...              ...      ...
P249990            1     8.47
P249991            1     3.38
P249993            5  1011.44
P249996            3    51.79
P249999            1    11.03

[24912 rows x 2 columns]

In [119]:
df.groupby('customer_age')['quantity'].sum()

customer_age
18     946
19    1042
20    1015
21     962
22     926
23     951
24     961
25    1149
26    1012
27     947
28    1002
29    1011
30     982
31     964
32     990
33    1013
34    1002
35     955
36     960
37    1013
38    1019
39     920
40     996
41    1056
42     961
43    1038
44     981
45    1010
46    1016
47    1015
48     995
49     909
50     977
51     977
52     910
53    1067
54    1007
55     954
56     996
57     986
58     949
59    1004
60    1004
61     972
62    1051
63     985
64     937
65     933
66     984
67     913
68    1012
69    1093
Name: quantity, dtype: int64

In [120]:
df.groupby(['customer_age', 'category']).agg({'quantity':'sum','price':'sum'})

                          quantity     price
customer_age category
18           Beauty            108   2041.56
             Electronics       185  52867.70
             Fashion           194   7412.68
             Grocery            79    955.99
             Home              148  13207.60
...                            ...       ...
69           Fashion           213   6512.40
             Grocery           168   1512.54
             Home              165  13501.28
             Sports            136   7762.64
             Toys              128   1958.40

[364 rows x 2 columns]

In [121]:
df.groupby('product_id').agg({'price':'sum','quantity': 'sum','shipping_cost':'sum'})

              price  quantity  shipping_cost
product_id
P200000      133.15         1           7.60
P200001      168.11         1           7.38
P200002      119.18         3           7.56
P200003       91.73         2          11.17
P200005        6.80         2           4.64
...             ...       ...            ...
P249990        8.47         1           2.16
P249991        3.38         1           1.68
P249993     1011.44         5          16.09
P249996       51.79         3           7.22
P249999       11.03         1           2.53

[24912 rows x 3 columns]

In [122]:
df.groupby('category').agg({'total_amount': 'sum','profit_margin': 'mean','order_id': 'count'})

             total_amount  profit_margin  order_id
category
Beauty          153019.38      11.990395      4103
Electronics    3319206.50      55.723587      6180
Fashion         471545.80      20.597162      6254
Grocery          82000.51      -2.264160      4058
Home           1077681.52      47.864717      5487
Sports          629825.54      38.485114      4171
Toys            132013.80       7.927773      4247

In [123]:
df['category'].value_counts()

category
Fashion        6254
Electronics    6180
Home           5487
Toys           4247
Sports         4171
Beauty         4103
Grocery        4058
Name: count, dtype: int64

In [124]:
df['returned'].value_counts()

returned
No     32597
Yes     1903
Name: count, dtype: int64

In [125]:
df.groupby('category')['total_amount'].sum()

category
Beauty          153019.38
Electronics    3319206.50
Fashion         471545.80
Grocery          82000.51
Home           1077681.52
Sports          629825.54
Toys            132013.80
Name: total_amount, dtype: float64

In [126]:
df.groupby('category')['profit_margin'].sum()

category
Beauty          49196.59
Electronics    344371.77
Fashion        128814.65
Grocery         -9187.96
Home           262633.70
Sports         160521.41
Toys            33669.25
Name: profit_margin, dtype: float64

In [127]:
df.groupby('customer_gender')['total_amount'].mean()

customer_gender
Female    169.657329
Male      171.248028
Other     159.577813
Name: total_amount, dtype: float64

In [128]:
df['customer_gender'].value_counts()

customer_gender
Female    16818
Male      16310
Other      1372
Name: count, dtype: int64

In [129]:
df['region'].value_counts()

region
South      7584
North      7572
East       6904
West       6808
Central    5632
Name: count, dtype: int64

In [130]:
 df.groupby('payment_method')['order_id'].count()

payment_method
COD             4160
Credit Card    12170
Debit Card      8505
PayPal          3444
UPI             4156
Wallet          2065
Name: order_id, dtype: int64

In [131]:
df.groupby('category')['returned'].value_counts()

category     returned
Beauty       No          3948
             Yes          155
Electronics  No          5729
             Yes          451
Fashion      No          5736
             Yes          518
Grocery      No          4005
             Yes           53
Home         No          5177
             Yes          310
Sports       No          3965
             Yes          206
Toys         No          4037
             Yes          210
Name: count, dtype: int64

In [132]:
df.groupby('category')['profit_margin'].mean()

category
Beauty         11.990395
Electronics    55.723587
Fashion        20.597162
Grocery        -2.264160
Home           47.864717
Sports         38.485114
Toys            7.927773
Name: profit_margin, dtype: float64

In [133]:
df.groupby('delivery_time_days')['returned'].count()

delivery_time_days
3      4907
4     10094
5     10296
6      5961
7      2400
8       663
9       152
10       25
12        1
13        1
Name: returned, dtype: int64

In [134]:
df.groupby('region')['total_amount'].sum()

region
Central     940503.38
East       1176334.75
North      1264008.35
South      1298096.07
West       1186350.50
Name: total_amount, dtype: float64

In [135]:
 df[df['delivery_time_days'] > 10]

,order_id,customer_id,product_id,category,price,discount,quantity,payment_method,order_date,delivery_time_days,region,returned,total_amount,shipping_cost,profit_margin,customer_age,customer_gender
1708,O101708,C10832,P237575,Fashion,22.14,0.0,2,Credit Card,2024-04-14,13,East,No,44.28,7.21,8.29,48,Female
7575,O107575,C14524,P223337,Fashion,7.46,0.0,1,Credit Card,2023-11-12,12,East,No,7.46,3.89,-1.28,39,Female

In [136]:
df[df['profit_margin'] < 0]

,order_id,customer_id,product_id,category,price,discount,quantity,payment_method,order_date,delivery_time_days,region,returned,total_amount,shipping_cost,profit_margin,customer_age,customer_gender
1,O100001,C17603,P228204,Grocery,24.73,0.00,1,Credit Card,2025-04-03,6,South,No,24.73,4.60,-2.62,37,Male
7,O100007,C13092,P216691,Beauty,9.98,0.00,1,Credit Card,2023-09-14,4,West,No,9.98,4.51,-0.02,66,Other
8,O100008,C15734,P202751,Fashion,6.61,0.05,1,Debit Card,2023-10-23,6,West,No,6.28,3.43,-1.23,37,Female
9,O100009,C16265,P207782,Grocery,10.91,0.00,1,Credit Card,2023-10-31,6,South,No,10.91,2.76,-1.89,56,Male
12,O100012,C14426,P245991,Grocery,10.56,0.10,1,Credit Card,2024-10-13,4,West,No,9.50,4.99,-4.23,22,Female
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34482,O134482,C13753,P218095,Grocery,5.19,0.05,1,UPI,2024-11-20,6,East,No,4.93,1.76,-1.37,33,Female
34488,O134488,C11459,P235070,Fashion,8.56,0.05,1,Credit Card,2023-10-09,4,South,No,8.13,3.48,-0.63,51,Other
34491,O134491,C17771,P231766,Grocery,14.33,0.00,1,Debit Card,2024-10-19,5,West,No,14.33,4.87,-3.72,67,Male
34492,O134492,C15268,P207561,Grocery,14.18,0.05,1,PayPal,2025-04-02,3,North,No,13.47,6.15,-5.07,35,Male
34495,O134495,C13553,P231412,Fashion,10.44,0.20,1,Debit Card,2025-08-13,3,North,No,8.35,3.04,-0.12,23,Female

In [137]:
 df[df['discount'] > 0.15]

,order_id,customer_id,product_id,category,price,discount,quantity,payment_method,order_date,delivery_time_days,region,returned,total_amount,shipping_cost,profit_margin,customer_age,customer_gender
15,O100015,C13444,P227609,Home,12.63,0.2,4,Credit Card,2024-05-03,3,North,No,40.42,6.19,5.13,36,Male
69,O100069,C12061,P203877,Grocery,3.96,0.2,1,PayPal,2023-11-22,5,East,No,3.17,3.06,-2.81,44,Female
76,O100076,C11363,P242368,Sports,23.23,0.3,2,Credit Card,2025-02-13,4,Central,No,32.52,5.10,4.66,31,Male
101,O100101,C16545,P215847,Home,37.39,0.2,1,Credit Card,2025-02-04,5,North,No,29.91,3.68,4.69,49,Male
104,O100104,C10161,P230123,Home,239.28,0.2,1,Credit Card,2024-11-14,4,South,No,191.42,8.60,45.00,69,Male
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34450,O134450,C17007,P224459,Fashion,45.48,0.2,1,Credit Card,2023-11-02,5,South,No,36.38,6.05,6.68,29,Male
34470,O134470,C13736,P216445,Toys,43.47,0.2,1,Credit Card,2024-11-04,6,East,No,34.78,4.30,9.61,48,Female
34475,O134475,C17096,P245751,Grocery,41.60,0.3,4,COD,2025-05-03,5,South,No,116.48,7.29,2.03,57,Female
34487,O134487,C13392,P241311,Fashion,33.92,0.2,4,PayPal,2024-12-26,5,East,No,108.54,6.69,31.30,24,Male
34495,O134495,C13553,P231412,Fashion,10.44,0.2,1,Debit Card,2025-08-13,3,North,No,8.35,3.04,-0.12,23,Female

In [138]:
df[df['profit_margin'] > 150]

,order_id,customer_id,product_id,category,price,discount,quantity,payment_method,order_date,delivery_time_days,region,returned,total_amount,shipping_cost,profit_margin,customer_age,customer_gender
18,O100018,C17831,P218405,Electronics,734.32,0.00,2,Wallet,2025-06-20,4,South,No,1468.64,10.90,165.34,58,Female
24,O100024,C15611,P247930,Sports,345.57,0.15,2,Debit Card,2024-04-16,5,Central,No,587.47,9.48,166.76,32,Female
51,O100051,C13005,P243043,Home,195.87,0.00,4,Credit Card,2024-12-31,5,West,No,783.48,10.37,209.00,43,Female
57,O100057,C11528,P246809,Home,167.21,0.00,4,Wallet,2023-12-06,3,North,No,668.84,8.88,178.40,37,Female
92,O100092,C13073,P230373,Electronics,857.18,0.00,3,COD,2024-08-10,4,West,No,2571.54,12.41,296.17,61,Female
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34277,O134277,C12863,P208412,Fashion,132.77,0.00,5,UPI,2025-02-06,5,West,No,663.85,9.48,222.87,63,Male
34315,O134315,C11836,P246145,Electronics,510.45,0.00,5,Credit Card,2024-07-07,5,North,No,2552.25,11.23,295.04,69,Male
34337,O134337,C13481,P245410,Electronics,999.34,0.05,2,Debit Card,2024-07-18,5,North,No,1898.75,12.75,215.10,31,Male
34361,O134361,C13082,P222530,Home,178.34,0.00,4,Credit Card,2024-02-14,5,North,No,713.36,9.43,190.31,52,Male
34497,O134497,C12986,P204345,Electronics,323.64,0.00,5,Credit Card,2025-02-01,6,East,No,1618.20,12.18,182.00,41,Female

In [139]:
df['month'] = df['order_date'].dt.month_name()
print(df['month'] )

0         December
1            April
2          October
3        September
4         December
           ...
34495       August
34496     December
34497     February
34498        March
34499    September
Name: month, Length: 34500, dtype: object

In [140]:
df.groupby('month')['order_id'].count()

month
April        2867
August       2876
December     2968
February     2695
January      2828
July         2972
June         2811
March        2904
May          2921
November     2859
October      2950
September    2849
Name: order_id, dtype: int64

In [141]:
df.groupby('month')['total_amount'].sum().sort_values(ascending=False)

month
December     533771.22
April        528620.69
October      521434.01
May          513402.69
July         502962.90
November     490858.95
March        487523.09
June         482931.66
September    461857.67
August       456421.70
February     443352.17
January      442156.30
Name: total_amount, dtype: float64

In [142]:
df['year'] = df['order_date'].dt.year

In [143]:
df.groupby('year')['order_id'].count()

year
2023     5228
2024    17133
2025    12139
Name: order_id, dtype: int64

In [144]:
df.groupby('year')['total_amount'].sum().sort_values(ascending=False)

year
2024    2931097.62
2025    2024653.15
2023     909542.28
Name: total_amount, dtype: float64

In [145]:
Remove_outlier= df[(df['profit_margin'] >= lower_bound) &(df['profit_margin'] <= upper_bound)]
Remove_outlier.head()

,order_id,customer_id,product_id,category,price,discount,quantity,payment_method,order_date,delivery_time_days,region,returned,total_amount,shipping_cost,profit_margin,customer_age,customer_gender,month,year
0,O100000,C17270,P234890,Home,164.08,0.15,1,Credit Card,2023-12-23,4,West,No,139.47,7.88,31.17,60,Female,December,2023
1,O100001,C17603,P228204,Grocery,24.73,0.00,1,Credit Card,2025-04-03,6,South,No,24.73,4.60,-2.62,37,Male,April,2025
2,O100002,C10860,P213892,Electronics,175.58,0.05,1,Credit Card,2024-10-08,4,North,No,166.80,6.58,13.44,34,Male,October,2024
3,O100003,C15390,P208689,Electronics,63.67,0.00,1,UPI,2024-09-14,6,South,No,63.67,5.50,2.14,21,Female,September,2024
4,O100004,C15226,P228063,Home,16.33,0.15,1,COD,2024-12-21,6,East,No,13.88,2.74,1.15,39,Male,December,2024

In [148]:
before_outliers = df.groupby('category')['profit_margin'].sum().sort_values(ascending=False)
print(before_outliers)

category
Electronics    344371.77
Home           262633.70
Sports         160521.41
Fashion        128814.65
Beauty          49196.59
Toys            33669.25
Grocery         -9187.96
Name: profit_margin, dtype: float64

In [149]:
after_outliers = Remove_outlier.groupby('category')['profit_margin'].sum().sort_values(ascending=False)
print(after_outliers)

category
Electronics    138386.36
Home           113302.80
Fashion         95295.50
Sports          84370.14
Beauty          42621.49
Toys            31147.90
Grocery         -9187.96
Name: profit_margin, dtype: float64